use=web, web=dynamicdns.park-your-domain.com/getip
protocol=namecheap
server=dynamicdns.park-your-domain.com
login=soulhatch.band
password={{ lookup('ansible.builtin.env', 'SOULHATCH_DDNS_PASSWORD') }}
listmonk
