use=web, web=dynamicdns.park-your-domain.com/getip
protocol=namecheap
server=dynamicdns.park-your-domain.com
login=weastie.com
password={{ ddns_password }}
immich

use=web, web=dynamicdns.park-your-domain.com/getip
protocol=namecheap
server=dynamicdns.park-your-domain.com
login=weastie.com
password={{ ddns_password }}
@

use=web, web=dynamicdns.park-your-domain.com/getip
protocol=namecheap
server=dynamicdns.park-your-domain.com
login=soulhatch.band
password={{ soulhatch_ddns_password }}
@

use=web, web=dynamicdns.park-your-domain.com/getip
protocol=namecheap
server=dynamicdns.park-your-domain.com
login=soulhatch.band
password={{ soulhatch_ddns_password }}
listmonk
